analyzer: fix int-conversion scope
catenacyber/perfsprint pull request #32
Opened 2024-11-18 21:45 UTC by ccoVeille

intConv parameter was introduced to disable some rules.

The code was introduced with e958370, but only a part of the rules
related to integer conversions were altered.

This commit completes what was done in the previous commit

2024-11-18 21:46 UTC, ccoVeille commented
Here is a suggestion I'm doing after trying to play with the config to disable some of the rules.

Please review, do not hesitate to tell me if I'm wrong with this idea. Thanks

cc @alexandear as I'm curious what he would think about it

2024-11-19 15:13 UTC, alexandear approved these changes

2024-11-19 20:10 UTC, catenacyber commented
Well, `intConv` was meant to be about integer conversion like `int64(a)` because it is less nice/readable code.

Why do you want to disable `fmt.Sprintf` to `strconv.Itoa` ?
If you really want, I guess it should be a new option

2024-11-20 07:02 UTC, ccoVeille commented
The idea is to be able to be able to disable everything via the configuration.

If someone only wants errrof and sprintf1, it should be possible.

I chose existing intConv variable because it feels like it was also about int conversion.

But maybe you are right. Also having a new variable will avoid breaking changes for people.

What would be the name of the variable according to you?

It's about integer formating, so maybe `intFormat`?

2024-11-20 08:55 UTC, ccoVeille commented
Just noticing with work @mmorel-35 here

https://github.com/catenacyber/perfsprint/pull/31#discussion_r1849865987

That at least format bool would need a configuration variable too

2024-11-20 08:57 UTC, alexandear requested changes
I propose adding new option instead of reusing existing `intConv`.

2024-11-20 09:04 UTC, alexandear commented
> The idea is to be able to be able to disable everything via the configuration.

@catenacyber to be more clear, we want something that is already present in `govet` or `revive`. These linters have options to turn off or turn on specific checkers or rules.

Take a look
https://github.com/golangci/golangci-lint/blob/4c04e0053f6e03920293ddd5a3c4750410d8cbc3/.golangci.reference.yml#L1741

https://github.com/golangci/golangci-lint/blob/4c04e0053f6e03920293ddd5a3c4750410d8cbc3/.golangci.reference.yml#L2306

2024-11-20 09:23 UTC, ccoVeille commented
> I propose adding new option instead of reusing existing `intConv`.

I agree. I'll use int format, add boolFormat and any other needed.

I'll also update the tests because "noconv" should contain them all

2024-11-20 12:41 UTC, catenacyber commented
> I agree. I'll use [intFormat](https://github.com/catenacyber/perfsprint/pull/32#issuecomment-2487668199), add [boolFormat](https://github.com/catenacyber/perfsprint/pull/32#issuecomment-2487933701) and any other needed.

Sounds good, waiting for this

2024-11-20 19:13 UTC, ccoVeille commented
Based on the changes made on

- #31

I'll wait it to be merged before working again on this PR.

The number of changes in the testdata will be crazy, I'll face too many conflicts.

So, let's wait

2024-11-21 22:43 UTC, ccoVeille commented
I'm now waiting for #38 to be merged

Then I can open a new PR.

@mmorel-35 do you plan to update all the tests the checker names (the one in TODO for now), or do you want me to do it in my PR ?

2024-11-22 06:43 UTC, ccoVeille commented
OK, so I can do it with my PR, as I will need to add configuration option for them.

2024-11-22 08:03 UTC, ccoVeille commented
Yes, exactly.

We also talked about bool-format

For the int-conv of int format I don't know.

But these are the things that will be reviewed when code is ready

2024-11-22 08:07 UTC, ccoVeille commented
But maybe the simplest would be for you to open a PR once #38 will be merged to add these checker name.

The things I'm doing in this PR can be addressed later

2025-02-05 13:13 UTC, catenacyber commented
Should be closed after https://github.com/catenacyber/perfsprint/pull/42 right ?

2025-02-05 20:20 UTC, closed without merging